export const locations = [
  { label: 'ID: 1, Earth (C-137)' },
  { label: 'ID: 2, Abadango' },
  { label: 'ID: 3, Citadel of Ricks' },
  { label: "ID: 4, Worldender's lair" },
  { label: 'ID: 5, Anatomy Park' },
  { label: 'ID: 6, Interdimensional Cable' },
  { label: 'ID: 7, Immortality Field Resort' },
  { label: 'ID: 8, Post-Apocalyptic Earth' },
  { label: 'ID: 9, Purge Planet' },
  { label: 'ID: 10, Venzenulon 7' },
  { label: 'ID: 11, Bepis 9' },
  { label: 'ID: 12, Cronenberg Earth' },
  { label: 'ID: 13, Nuptia 4' },
  { label: "ID: 14, Giant's Town" },
  { label: 'ID: 15, Bird World' },
  { label: 'ID: 16, St. Gloopy Noops Hospital' },
  { label: 'ID: 17, Earth (5-126)' },
  { label: "ID: 18, Mr. Goldenfold's dream" },
  { label: 'ID: 19, Gromflom Prime' },
  { label: 'ID: 20, Earth (Replacement Dimension)' },
  { label: 'ID: 21, Testicle Monster Dimension' },
  { label: 'ID: 22, Signus 5 Expanse' },
  { label: 'ID: 23, Earth (C-500A)' },
  { label: "ID: 24, Rick's Battery Microverse" },
  { label: 'ID: 25, The Menagerie' },
  { label: 'ID: 26, Earth (K-83)' },
  { label: 'ID: 27, Hideout Planet' },
  { label: "ID: 28, Unity's Planet" },
  { label: 'ID: 29, Dorian 5' },
  { label: 'ID: 30, Earth (Unknown dimension)' },
  { label: 'ID: 31, Earth (J19ζ7)' },
  { label: 'ID: 32, Roy: A Life Well Lived' },
  { label: 'ID: 33, Eric Stoltz Mask Earth' },
  { label: "ID: 34, Earth (Evil Rick's Target Dimension)" },
  { label: 'ID: 35, Planet Squanch' },
  { label: 'ID: 36, Glaagablaaga' },
  { label: 'ID: 37, Resort Planet' },
  { label: 'ID: 38, Interdimensional Customs' },
  { label: 'ID: 39, Galactic Federation Prison' },
  { label: 'ID: 40, Gazorpazorp' },
  { label: 'ID: 41, Hamster in Butt World' },
  { label: 'ID: 42, Earth (Giant Telepathic Spiders Dimension)' },
  { label: 'ID: 43, Alphabetrium' },
  { label: 'ID: 44, Jerryboree' },
  { label: 'ID: 45, Krootabulon' },
  { label: "ID: 46, Zigerion's Base" },
  { label: 'ID: 47, Pluto' },
  { label: 'ID: 48, Fantasy World' },
  { label: "ID: 49, Zeep Xanflorp's Miniverse" },
  { label: "ID: 50, Kyle's Teenyverse" },
  { label: "ID: 51, Larva Alien's Planet" },
  { label: 'ID: 52, Earth (K-22)' },
  { label: 'ID: 53, Mr. Meeseeks Box' },
  { label: "ID: 54, Vindicator's Base" },
  { label: 'ID: 55, Pawn Shop Planet' },
  { label: 'ID: 56, Mega Gargantuan Kingdom' },
  { label: 'ID: 57, Gear World' },
  { label: 'ID: 58, Earth (D-99)' },
  { label: 'ID: 59, Earth (D716)' },
  { label: 'ID: 60, Earth (D716-B)' },
  { label: 'ID: 61, Earth (D716-C)' },
  { label: 'ID: 62, Earth (J-22)' },
  { label: 'ID: 63, Froopyland' },
  { label: 'ID: 64, Detoxifier' },
  { label: 'ID: 65, Trunk World' },
  { label: 'ID: 66, Plopstar' },
  { label: 'ID: 67, Blips and Chitz' },
  { label: 'ID: 68, Girvonesk' },
  { label: 'ID: 69, Earth (C-35)' },
  { label: "ID: 70, Snuffles' Dream" },
  { label: 'ID: 71, Earth (Pizza Dimension)' },
  { label: 'ID: 72, Earth (Phone Dimension)' },
  { label: 'ID: 73, Greasy Grandma World' },
  { label: 'ID: 74, Earth (Chair Dimension)' },
  { label: 'ID: 75, Árboles Mentirosos' },
  { label: 'ID: 76, Alien Day Spa' },
  { label: 'ID: 77, Earth (Fascist Dimension)' },
  { label: 'ID: 78, Snake Planet' },
  { label: 'ID: 79, Forbodulon Prime' },
  { label: 'ID: 80, Earth (Fascist Shrimp Dimension)' },
  { label: 'ID: 81, Earth (Fascist Teddy Bear Dimension)' },
  { label: 'ID: 82, Earth (Wasp Dimension)' },
  { label: 'ID: 83, Monogatron Mothership' },
  { label: 'ID: 84, Gorgon Quadrant' },
  { label: 'ID: 85, Midland Quasar' },
  { label: 'ID: 86, Mount Space Everest' },
  { label: 'ID: 87, Globaflyn' },
  { label: 'ID: 88, Heist-Con' },
  { label: 'ID: 89, Heistotron Base' },
  { label: 'ID: 90, Mount Olympus' },
  { label: 'ID: 91, Plitzville Montana' },
  { label: 'ID: 92, Earth (Tusk Dimension)' },
  { label: 'ID: 93, Gramuflack' },
  { label: 'ID: 94, Draygon' },
  { label: 'ID: 95, New Improved Galactic Federation Quarters' },
  { label: 'ID: 96, Story Train' },
  { label: 'ID: 97, Non-Diegetic Alternative Reality' },
  { label: 'ID: 98, Tickets Please Guy Nightmare' },
  { label: 'ID: 99, Morty’s Story' },
  { label: 'ID: 100, Ricks’s Story' },
  { label: 'ID: 101, Glorzo Asteroid' },
  { label: 'ID: 102, Alien Acid Plant' },
  { label: 'ID: 103, Merged Universe' },
  { label: 'ID: 104, Near-Duplicate Reality' },
  { label: 'ID: 105, NX-5 Planet Remover' },
  { label: 'ID: 106, Gaia' },
  { label: "ID: 107, Defiance's Ship" },
  { label: "ID: 108, Defiance's Base" },
  { label: 'ID: 109, The Ocean' },
  { label: 'ID: 110, Narnia Dimension' },
  { label: 'ID: 111, Elemental Rings' },
  { label: 'ID: 112, Morglutz' },
  { label: 'ID: 113, Ferkus 9' },
  { label: 'ID: 114, Morty' },
  { label: 'ID: 115, Space' },
  { label: 'ID: 116, Hell' },
  { label: 'ID: 117, Z. Q. P. D.' },
  { label: 'ID: 118, Space Tahoe' },
  { label: 'ID: 119, France' },
  { label: "ID: 120, Birdperson's Consciousness" },
  { label: "ID: 121, Rick's Consciousness" },
  { label: 'ID: 122, Avian Planet' },
  { label: 'ID: 123, Normal Size Bug Dimension' },
  { label: 'ID: 124, Slartivart' },
  { label: 'ID: 125, Rick and Two Crows Planet' },
  { label: "ID: 126, Rick's Memories" },
];
